import Head from 'next/head'

import Landing from '../components/Landing'
import Sidebar_left from '../components/Sidebar_left'
import Sidebar_right from '../components/Sidebar_right'

export default function Home() {
  return (
    <div className='bg-purple px-52'>
      <Head>
        <title>Vladimir Aleksic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Landing />
      <Sidebar_left />
      <Sidebar_right />
    </div>
  )
}
