import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Vladimir Aleksic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className='text-3xl font-bold underline'>Hello World!</h1>
      </main>
    </div>
  )
}
